//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cate
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string NameCode { get; set; }
        public Nullable<System.DateTime> Create_Day { get; set; }
        public Nullable<System.DateTime> Change_Day { get; set; }
        public string flag { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Sort { get; set; }
    }
}
