//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerBuy
    {
        public int Id { get; set; }
        public Nullable<int> IdCustomer { get; set; }
        public string NameProduct { get; set; }
        public Nullable<double> PriceProduct { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Size { get; set; }
        public Nullable<System.DateTime> Create_Day { get; set; }
        public Nullable<System.DateTime> Change_Day { get; set; }
        public string flag { get; set; }
        public Nullable<int> IdProduct { get; set; }
    }
}
