//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Adress { get; set; }
        public string Phone { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<System.DateTime> Create_Day { get; set; }
        public Nullable<System.DateTime> Change_Day { get; set; }
        public Nullable<int> IdProduct { get; set; }
        public string flag { get; set; }
        public Nullable<int> Status { get; set; }
        public string Note { get; set; }
        public string Email { get; set; }
    }
}
